## Installation
Clicke [here](https://www.tensorflow.org/install) for detailed information.
If you have pip installed use
    
    pip install tensorflow
    
If you have tensorflow installed successfully then you will be able to import this without any error.

In [2]:
import tensorflow as tf
print(tf.__version__)

2.3.0


## To see the physical devices, whether you have gpu support or not

In [22]:
gpu_devices = tf.config.list_physical_devices("GPU")
cpu_devices = tf.config.list_physical_devices("CPU")
print(f'CPU: {cpu_devices}, GPU: {gpu_devices}')

CPU: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')], GPU: []


## Basics of Tensors

In [21]:
# scalar, rank-0
x = tf.constant(4)
print(x)

x = tf.constant(4, shape = (1, 1))
print(x)

x = tf.constant(4, shape = (1, 1), dtype = tf.float32)
print(x)

# vector, rank-1 tensor
x = tf.constant([1, 2, 3, 4], dtype = tf.float32)
print(x)

# matrix, rank-2 tensor
x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]], dtype = tf.float32)
print(x)

x = tf.random.normal((3, 3), mean = 0, stddev = 1)
print(x)

x = tf.random.uniform((3, 3), minval = 0, maxval = 1)
print(x)

x = tf.range(10)
print(x)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([[4]], shape=(1, 1), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-1.797357    0.6587469  -0.47406766]
 [ 1.9142369   0.31566665  0.05880994]
 [-0.110662   -1.2397302  -1.0734788 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.6457505  0.6081101  0.829921  ]
 [0.60173917 0.50384724 0.591313  ]
 [0.13897312 0.18574655 0.9755291 ]], shape=(3, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


## Type Casting

In [25]:
x = tf.range(10)
print(x)

x = tf.cast(x, dtype = tf.float32)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


## Operations

In [36]:
# Element wise
x = tf.constant([1, 2, 3, 4])
y = tf.constant([5, 6, 7, 8])

z = tf.add(x, y)
print(z)

z = x + y
print(z)

z = tf.subtract(x, y)
print(z)

z = x - y
print(z)

z = tf.multiply(x, y)
print(z)

z = x * y
print(z)

z = tf.divide(x, y)
print(z)

z = x / y
print(z)

z = x ** 3
print(z)

# Dot Product
z = tf.tensordot(x, y, axes = 1)
print(z)
z = tf.tensordot(x, y, axes = 0)
print(z)

tf.Tensor([ 6  8 10 12], shape=(4,), dtype=int32)
tf.Tensor([ 6  8 10 12], shape=(4,), dtype=int32)
tf.Tensor([-4 -4 -4 -4], shape=(4,), dtype=int32)
tf.Tensor([-4 -4 -4 -4], shape=(4,), dtype=int32)
tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)
tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)
tf.Tensor([0.2        0.33333333 0.42857143 0.5       ], shape=(4,), dtype=float64)
tf.Tensor([0.2        0.33333333 0.42857143 0.5       ], shape=(4,), dtype=float64)
tf.Tensor([ 1  8 27 64], shape=(4,), dtype=int32)
tf.Tensor(70, shape=(), dtype=int32)
tf.Tensor(
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]], shape=(4, 4), dtype=int32)


## Matrix Multiplication
Shape of two matrix must satisfy the condition no. of columns in A = no. of rows in B

In [40]:
A = tf.random.normal((3, 5))
B = tf.random.normal((5, 4))
z = tf.matmul(A, B)
print(z)

z = A @ B
print(z)

tf.Tensor(
[[-0.706614   -0.27849272 -0.42634264  1.0168637 ]
 [-1.5816188   2.0442917  -0.08215138 -0.9442664 ]
 [ 4.3223267  -3.2489266   2.655306    1.0111902 ]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-0.706614   -0.27849272 -0.42634264  1.0168637 ]
 [-1.5816188   2.0442917  -0.08215138 -0.9442664 ]
 [ 4.3223267  -3.2489266   2.655306    1.0111902 ]], shape=(3, 4), dtype=float32)


## Indexing, Slicing

In [46]:
x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x[0]) # print all elements in row 0
print(x[:, 0]) # print first column of all rows
print(x[0, :]) # row 0, all column
print(x[1, 3]) # element at row 1, col 3

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 5], shape=(2,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


## Reshape

In [57]:
x = tf.random.normal((3, 4))
print(x)

y = tf.reshape(x, (4, 3))
print(y)

z = tf.reshape(x, (-1, 6))
print(z)

w = tf.reshape(x, (12))
print(w)

tf.Tensor(
[[-3.189018   -0.8142106  -0.5404986   0.69513977]
 [-0.3005964  -2.7341373  -0.73818946  1.692412  ]
 [-1.046133    2.4126778  -0.16878179  0.24925807]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-3.189018   -0.8142106  -0.5404986 ]
 [ 0.69513977 -0.3005964  -2.7341373 ]
 [-0.73818946  1.692412   -1.046133  ]
 [ 2.4126778  -0.16878179  0.24925807]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[-3.189018   -0.8142106  -0.5404986   0.69513977 -0.3005964  -2.7341373 ]
 [-0.73818946  1.692412   -1.046133    2.4126778  -0.16878179  0.24925807]], shape=(2, 6), dtype=float32)
tf.Tensor(
[-3.189018   -0.8142106  -0.5404986   0.69513977 -0.3005964  -2.7341373
 -0.73818946  1.692412   -1.046133    2.4126778  -0.16878179  0.24925807], shape=(12,), dtype=float32)


## Tensor Numpy Conversion

In [63]:
x = tf.random.normal((3, 4))
print(x)
y = x.numpy()
print(y, type(y))

z = tf.convert_to_tensor(y)
print(z)

tf.Tensor(
[[ 0.5436713  -2.5905402  -2.2644565   0.13325548]
 [ 1.1554288  -1.7146541   0.6170969  -1.6931981 ]
 [-0.44344088  0.08656792  0.7424788  -1.901758  ]], shape=(3, 4), dtype=float32)
[[ 0.5436713  -2.5905402  -2.2644565   0.13325548]
 [ 1.1554288  -1.7146541   0.6170969  -1.6931981 ]
 [-0.44344088  0.08656792  0.7424788  -1.901758  ]] <class 'numpy.ndarray'>
tf.Tensor(
[[ 0.5436713  -2.5905402  -2.2644565   0.13325548]
 [ 1.1554288  -1.7146541   0.6170969  -1.6931981 ]
 [-0.44344088  0.08656792  0.7424788  -1.901758  ]], shape=(3, 4), dtype=float32)
